const READ_TODOS = 'READ_TODOS';
const ADD_TODO = 'ADD_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';

export { READ_TODOS, ADD_TODO, UPDATE_TODO, DELETE_TODO, COMPLETE_TODO };
