const TODO_SORTING_CATEGORIES = {
  TODO_TITLE: 'TODO_TITLE',
  TODO_PRIORITY: 'TODO_PRIORITY',
  TODO_CREATED_AT: 'TODO_CREATED_AT',
  TODO_UPDATED_AT: 'TODO_UPDATED_AT',
  TODO_IS_GOING: 'TODO_IS_GOING',
  TODO_IS_COMPLETED: 'TODO_IS_COMPLETED',
  TODO_EMAIL: 'TODO_EMAIL',
  TODO_REMAIN_TIME: 'TODO_REMAIN_TIME',
};

const SORT_DIRECTION = {
  ASC: 'ASCENDING',
  DESC: 'DESCENDING',
};

function flipSortDirection(oldDirection) {
  return oldDirection === SORT_DIRECTION.ASC
    ? SORT_DIRECTION.DESC
    : SORT_DIRECTION.ASC;
}

const ROW_PER_PAGE_DEFAULT = 10;

export {
  TODO_SORTING_CATEGORIES,
  SORT_DIRECTION,
  flipSortDirection,
  ROW_PER_PAGE_DEFAULT,
};
